hostname: DC1-SPINE2
metadata:
  platform: vEOS-LAB
is_deployed: true
router_bgp:
  as: '65001'
  router_id: 192.168.255.2
  bgp_defaults:
  - no bgp default ipv4-unicast
  - distance bgp 20 200 200
  - graceful-restart restart-time 300
  - graceful-restart
  bgp:
    default:
      ipv4_unicast: false
  maximum_paths:
    paths: 4
    ecmp: 4
  updates:
    wait_install: true
  peer_groups:
  - name: IPv4-UNDERLAY-PEERS
    type: ipv4
    password: AQQvKeimxJu+uGQ/yYvv9w==
    maximum_routes: 12000
    send_community: all
  - name: EVPN-OVERLAY-PEERS
    type: evpn
    update_source: Loopback0
    bfd: true
    password: q+VNViP5i4rVjW1cxFv2wA==
    send_community: all
    maximum_routes: 0
    ebgp_multihop: 3
    next_hop_unchanged: true
  address_family_ipv4:
    peer_groups:
    - name: IPv4-UNDERLAY-PEERS
      activate: true
    - name: EVPN-OVERLAY-PEERS
      activate: false
  redistribute_routes:
  - source_protocol: connected
    route_map: RM-CONN-2-BGP
  neighbors:
  - ip_address: 172.31.255.3
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65101'
    peer: DC1-LEAF1A
    description: DC1-LEAF1A_Ethernet2
  - ip_address: 172.31.255.7
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65101'
    peer: DC1-LEAF1B
    description: DC1-LEAF1B_Ethernet2
  - ip_address: 172.31.255.11
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65102'
    peer: DC1-LEAF2A
    description: DC1-LEAF2A_Ethernet2
  - ip_address: 172.31.255.15
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65102'
    peer: DC1-LEAF2B
    description: DC1-LEAF2B_Ethernet2
  - ip_address: 192.168.255.3
    peer_group: EVPN-OVERLAY-PEERS
    peer: DC1-LEAF1A
    description: DC1-LEAF1A
    remote_as: '65101'
  - ip_address: 192.168.255.4
    peer_group: EVPN-OVERLAY-PEERS
    peer: DC1-LEAF1B
    description: DC1-LEAF1B
    remote_as: '65101'
  - ip_address: 192.168.255.5
    peer_group: EVPN-OVERLAY-PEERS
    peer: DC1-LEAF2A
    description: DC1-LEAF2A
    remote_as: '65102'
  - ip_address: 192.168.255.6
    peer_group: EVPN-OVERLAY-PEERS
    peer: DC1-LEAF2B
    description: DC1-LEAF2B
    remote_as: '65102'
  address_family_evpn:
    peer_groups:
    - name: EVPN-OVERLAY-PEERS
      activate: true
static_routes:
- vrf: MGMT
  destination_address_prefix: 0.0.0.0/0
  gateway: 10.255.0.1
service_routing_protocols_model: multi-agent
ip_routing: true
daemon_terminattr:
  cvaddrs:
  - 10.255.0.1:9910
  cvauth:
    method: key
    key: ''
  cvvrf: MGMT
  smashexcludes: ale,flexCounter,hardware,kni,pulse,strata
  ingestexclude: /Sysdb/cell/1/agent,/Sysdb/cell/2/agent
  disable_aaa: false
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
ip_name_servers:
- ip_address: 192.168.2.1
  vrf: MGMT
- ip_address: 8.8.8.8
  vrf: MGMT
spanning_tree:
  mode: none
local_users:
- name: admin
  privilege: 15
  role: network-admin
  sha512_password: $6$Df86J4/SFMDE3/1K$Hef4KstdoxNDaami37cBquTWOTplC.miMPjXVgQxMe92.e5wxlnXOLlebgPj8Fz1KO0za/RCO7ZIs4Q6Eiq1g1
- name: ansible
  privilege: 15
  role: network-admin
  sha512_password: $6$Dzu11L7yp9j3nCM9$FSptxMPyIL555OMO.ldnjDXgwZmrfMYwHSr0uznE5Qoqvd9a6UdjiFcJUhGLtvXVZR1r.A/iF5aAt50hf/EK4/
- name: cvpadmin
  privilege: 15
  role: network-admin
  sha512_password: $6$rZKcbIZ7iWGAWTUM$TCgDn1KcavS0s.OV8lacMTUkxTByfzcGlFlYUWroxYuU7M/9bIodhRO7nXGzMweUxvbk8mJmQl8Bh44cRktUj.
vrfs:
- name: MGMT
  ip_routing: false
management_interfaces:
- name: Management1
  description: oob_management
  shutdown: false
  vrf: MGMT
  ip_address: 10.255.0.12/24
  gateway: 10.255.0.1
  type: oob
management_api_http:
  enable_vrfs:
  - name: MGMT
  enable_https: true
ethernet_interfaces:
- name: Ethernet1
  peer: DC1-LEAF1A
  peer_interface: Ethernet2
  peer_type: l3leaf
  description: P2P_LINK_TO_DC1-LEAF1A_Ethernet2
  shutdown: false
  mtu: 1500
  type: routed
  ip_address: 172.31.255.2/31
- name: Ethernet2
  peer: DC1-LEAF1B
  peer_interface: Ethernet2
  peer_type: l3leaf
  description: P2P_LINK_TO_DC1-LEAF1B_Ethernet2
  shutdown: false
  mtu: 1500
  type: routed
  ip_address: 172.31.255.6/31
- name: Ethernet3
  peer: DC1-LEAF2A
  peer_interface: Ethernet2
  peer_type: l3leaf
  description: P2P_LINK_TO_DC1-LEAF2A_Ethernet2
  shutdown: false
  mtu: 1500
  type: routed
  ip_address: 172.31.255.10/31
- name: Ethernet4
  peer: DC1-LEAF2B
  peer_interface: Ethernet2
  peer_type: l3leaf
  description: P2P_LINK_TO_DC1-LEAF2B_Ethernet2
  shutdown: false
  mtu: 1500
  type: routed
  ip_address: 172.31.255.14/31
loopback_interfaces:
- name: Loopback0
  description: EVPN_Overlay_Peering
  shutdown: false
  ip_address: 192.168.255.2/32
prefix_lists:
- name: PL-LOOPBACKS-EVPN-OVERLAY
  sequence_numbers:
  - sequence: 10
    action: permit 192.168.255.0/24 eq 32
route_maps:
- name: RM-CONN-2-BGP
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
router_bfd:
  multihop:
    interval: 1200
    min_rx: 1200
    multiplier: 3
ntp:
  local_interface:
    name: Management1
    vrf: MGMT
  servers:
  - name: 0.fr.pool.ntp.org
    preferred: true
    vrf: MGMT
  - name: 1.fr.pool.ntp.org
    vrf: MGMT
