hostname: DC1-L2LEAF1A
metadata:
  platform: vEOS-LAB
is_deployed: true
static_routes:
- vrf: MGMT
  destination_address_prefix: 0.0.0.0/0
  gateway: 10.255.0.1
service_routing_protocols_model: multi-agent
daemon_terminattr:
  cvaddrs:
  - 10.255.0.1:9910
  cvauth:
    method: key
    key: ''
  cvvrf: MGMT
  smashexcludes: ale,flexCounter,hardware,kni,pulse,strata
  ingestexclude: /Sysdb/cell/1/agent,/Sysdb/cell/2/agent
  disable_aaa: false
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
ip_name_servers:
- ip_address: 192.168.2.1
  vrf: MGMT
- ip_address: 8.8.8.8
  vrf: MGMT
spanning_tree:
  mode: mstp
  mst_instances:
  - id: '0'
    priority: 16384
local_users:
- name: admin
  privilege: 15
  role: network-admin
  sha512_password: $6$Df86J4/SFMDE3/1K$Hef4KstdoxNDaami37cBquTWOTplC.miMPjXVgQxMe92.e5wxlnXOLlebgPj8Fz1KO0za/RCO7ZIs4Q6Eiq1g1
- name: ansible
  privilege: 15
  role: network-admin
  sha512_password: $6$Dzu11L7yp9j3nCM9$FSptxMPyIL555OMO.ldnjDXgwZmrfMYwHSr0uznE5Qoqvd9a6UdjiFcJUhGLtvXVZR1r.A/iF5aAt50hf/EK4/
- name: cvpadmin
  privilege: 15
  role: network-admin
  sha512_password: $6$rZKcbIZ7iWGAWTUM$TCgDn1KcavS0s.OV8lacMTUkxTByfzcGlFlYUWroxYuU7M/9bIodhRO7nXGzMweUxvbk8mJmQl8Bh44cRktUj.
vrfs:
- name: MGMT
  ip_routing: false
management_interfaces:
- name: Management1
  description: oob_management
  shutdown: false
  vrf: MGMT
  ip_address: 10.255.0.17/24
  gateway: 10.255.0.1
  type: oob
management_api_http:
  enable_vrfs:
  - name: MGMT
  enable_https: true
ethernet_interfaces:
- name: Ethernet1
  peer: DC1-LEAF1A
  peer_interface: Ethernet5
  peer_type: l3leaf
  description: DC1-LEAF1A_Ethernet5
  shutdown: false
  type: port-channel-member
  channel_group:
    id: 1
    mode: active
- name: Ethernet2
  peer: DC1-LEAF1B
  peer_interface: Ethernet5
  peer_type: l3leaf
  description: DC1-LEAF1B_Ethernet5
  shutdown: false
  type: port-channel-member
  channel_group:
    id: 1
    mode: active
- name: Ethernet5
  peer: server01
  peer_interface: Eth0
  peer_type: server
  port_profile: TENANT_A
  description: server01_Eth0
  shutdown: false
  type: switched
  mode: access
  vlans: '110'
port_channel_interfaces:
- name: Port-Channel1
  description: DC1_LEAF1_Po5
  type: switched
  shutdown: false
  mode: trunk
  vlans: 110-112,120-121,130-131
vlans:
- id: 130
  name: Tenant_A_APP_Zone_1
  tenant: Tenant_A
- id: 131
  name: Tenant_A_APP_Zone_2
  tenant: Tenant_A
- id: 110
  name: Tenant_A_OP_Zone_1
  tenant: Tenant_A
- id: 111
  name: Tenant_A_OP_Zone_2
  tenant: Tenant_A
- id: 112
  name: Tenant_A_OP_Zone_3
  tenant: Tenant_A
- id: 120
  name: Tenant_A_WEB_Zone_1
  tenant: Tenant_A
- id: 121
  name: Tenant_A_WEBZone_2
  tenant: Tenant_A
ip_igmp_snooping:
  globally_enabled: true
ntp:
  local_interface:
    name: Management1
    vrf: MGMT
  servers:
  - name: 0.fr.pool.ntp.org
    preferred: true
    vrf: MGMT
  - name: 1.fr.pool.ntp.org
    vrf: MGMT
