static_routes:
- vrf: MGMT
  destination_address_prefix: 0.0.0.0/0
  gateway: 192.168.0.1
service_routing_protocols_model: multi-agent
ip_routing: true
daemon_terminattr:
  cvaddrs:
  - 192.168.0.1:9910
  cvauth:
    method: token
    key: ''
    token_file: /tmp/token
  cvvrf: MGMT
  smashexcludes: ale,flexCounter,hardware,kni,pulse,strata
  ingestexclude: /Sysdb/cell/1/agent,/Sysdb/cell/2/agent
  disable_aaa: false
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
name_server:
  source:
    vrf: MGMT
  nodes:
  - 192.168.0.1
  - 8.8.8.8
spanning_tree:
  mode: mstp
  mst_instances:
    '0':
      priority: 16384
local_users:
  admin:
    privilege: 15
    role: network-admin
    sha512_password: $6$Df86J4/SFMDE3/1K$Hef4KstdoxNDaami37cBquTWOTplC.miMPjXVgQxMe92.e5wxlnXOLlebgPj8Fz1KO0za/RCO7ZIs4Q6Eiq1g1
  ansible:
    privilege: 15
    role: network-admin
    sha512_password: $6$Dzu11L7yp9j3nCM9$FSptxMPyIL555OMO.ldnjDXgwZmrfMYwHSr0uznE5Qoqvd9a6UdjiFcJUhGLtvXVZR1r.A/iF5aAt50hf/EK4/
  cvpadmin:
    privilege: 15
    role: network-admin
    sha512_password: $6$4828$a9aaPzwYjB1V1ArjILOFtE92LhQuSern18Y8mn8sAphBYiICSiut2AgkYT7oLxOmk3bhgDo4UOEmtAeb.ZZvO/
vrfs:
  MGMT:
    ip_routing: false
management_interfaces:
  Management1:
    description: oob_management
    shutdown: false
    vrf: MGMT
    ip_address: 192.168.0.17/24
    gateway: 192.168.0.1
    type: oob
management_api_http:
  enable_vrfs:
    MGMT: {}
  enable_https: true
ethernet_interfaces:
  Ethernet1:
    peer: DC1-LEAF1A
    peer_interface: Ethernet5
    peer_type: l3leaf
    description: DC1-LEAF1A_Ethernet5
    type: switched
    shutdown: false
    channel_group:
      id: 1
      mode: active
  Ethernet2:
    peer: DC1-LEAF1B
    peer_interface: Ethernet5
    peer_type: l3leaf
    description: DC1-LEAF1B_Ethernet5
    type: switched
    shutdown: false
    channel_group:
      id: 1
      mode: active
  Ethernet5:
    peer: server01
    peer_interface: Eth0
    peer_type: server
    description: server01_Eth0
    type: switched
    shutdown: false
    mode: access
    vlans: 110
port_channel_interfaces:
  Port-Channel1:
    description: DC1_LEAF1_Po5
    type: switched
    shutdown: false
    vlans: 110-112,120-121,130-131
    mode: trunk
vlans:
  130:
    tenant: Tenant_A
    name: Tenant_A_APP_Zone_1
  131:
    tenant: Tenant_A
    name: Tenant_A_APP_Zone_2
  110:
    tenant: Tenant_A
    name: Tenant_A_OP_Zone_1
  111:
    tenant: Tenant_A
    name: Tenant_A_OP_Zone_2
  112:
    tenant: Tenant_A
    name: Tenant_A_OP_Zone_3
  120:
    tenant: Tenant_A
    name: Tenant_A_WEB_Zone_1
  121:
    tenant: Tenant_A
    name: Tenant_A_WEBZone_2
ip_igmp_snooping:
  globally_enabled: true
ntp:
  local_interface:
    name: Management1
    vrf: MGMT
  servers:
  - name: 0.fr.pool.ntp.org
    preferred: true
    vrf: MGMT
  - name: 1.fr.pool.ntp.org
    vrf: MGMT
