router_bgp:
  as: '65001'
  router_id: 192.168.255.1
  bgp_defaults:
  - no bgp default ipv4-unicast
  - distance bgp 20 200 200
  - graceful-restart restart-time 300
  - graceful-restart
  - maximum-paths 4 ecmp 4
  peer_groups:
    IPv4-UNDERLAY-PEERS:
      type: ipv4
      password: AQQvKeimxJu+uGQ/yYvv9w==
      maximum_routes: 12000
      send_community: all
    EVPN-OVERLAY-PEERS:
      type: evpn
      update_source: Loopback0
      bfd: true
      ebgp_multihop: '3'
      password: q+VNViP5i4rVjW1cxFv2wA==
      send_community: all
      maximum_routes: 0
      next_hop_unchanged: true
  address_family_ipv4:
    peer_groups:
      IPv4-UNDERLAY-PEERS:
        activate: true
      EVPN-OVERLAY-PEERS:
        activate: false
  redistribute_routes:
    connected:
      route_map: RM-CONN-2-BGP
  neighbors:
    172.31.255.1:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '65101'
      description: DC1-LEAF1A_Ethernet1
    172.31.255.5:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '65101'
      description: DC1-LEAF1B_Ethernet1
    172.31.255.9:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '65102'
      description: DC1-LEAF2A_Ethernet1
    172.31.255.13:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '65102'
      description: DC1-LEAF2B_Ethernet1
    192.168.255.3:
      peer_group: EVPN-OVERLAY-PEERS
      description: DC1-LEAF1A
      remote_as: '65101'
    192.168.255.4:
      peer_group: EVPN-OVERLAY-PEERS
      description: DC1-LEAF1B
      remote_as: '65101'
    192.168.255.5:
      peer_group: EVPN-OVERLAY-PEERS
      description: DC1-LEAF2A
      remote_as: '65102'
    192.168.255.6:
      peer_group: EVPN-OVERLAY-PEERS
      description: DC1-LEAF2B
      remote_as: '65102'
  address_family_evpn:
    peer_groups:
      EVPN-OVERLAY-PEERS:
        activate: true
static_routes:
- vrf: MGMT
  destination_address_prefix: 0.0.0.0/0
  gateway: 192.168.0.5
service_routing_protocols_model: multi-agent
ip_routing: true
daemon_terminattr:
  cvaddrs:
  - 192.168.0.5:9910
  cvauth:
    method: key
    key: ''
  cvvrf: MGMT
  smashexcludes: ale,flexCounter,hardware,kni,pulse,strata
  ingestexclude: /Sysdb/cell/1/agent,/Sysdb/cell/2/agent
  disable_aaa: false
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
name_server:
  source:
    vrf: MGMT
  nodes:
  - 192.168.0.5
  - 8.8.8.8
spanning_tree:
  mode: none
local_users:
  admin:
    privilege: 15
    role: network-admin
    sha512_password: $6$Df86J4/SFMDE3/1K$Hef4KstdoxNDaami37cBquTWOTplC.miMPjXVgQxMe92.e5wxlnXOLlebgPj8Fz1KO0za/RCO7ZIs4Q6Eiq1g1
  ansible:
    privilege: 15
    role: network-admin
    sha512_password: $6$Dzu11L7yp9j3nCM9$FSptxMPyIL555OMO.ldnjDXgwZmrfMYwHSr0uznE5Qoqvd9a6UdjiFcJUhGLtvXVZR1r.A/iF5aAt50hf/EK4/
  cvpadmin:
    privilege: 15
    role: network-admin
    sha512_password: $6$13994$MwG2qno1XZb8XXmxtsnzpFApf52gCQ7q/8mTu3drfQ7lDezXZDq0.2aTcCHdVt/0OUi4.PRjrZnLJI6lIUz7U1
vrfs:
  MGMT:
    ip_routing: false
management_interfaces:
  Management1:
    description: oob_management
    shutdown: false
    vrf: MGMT
    ip_address: 192.168.0.11/24
    gateway: 192.168.0.5
    type: oob
management_api_http:
  enable_vrfs:
    MGMT: {}
  enable_https: true
ethernet_interfaces:
  Ethernet1:
    peer: DC1-LEAF1A
    peer_interface: Ethernet1
    peer_type: l3leaf
    description: P2P_LINK_TO_DC1-LEAF1A_Ethernet1
    mtu: 1500
    type: routed
    shutdown: false
    ip_address: 172.31.255.0/31
  Ethernet2:
    peer: DC1-LEAF1B
    peer_interface: Ethernet1
    peer_type: l3leaf
    description: P2P_LINK_TO_DC1-LEAF1B_Ethernet1
    mtu: 1500
    type: routed
    shutdown: false
    ip_address: 172.31.255.4/31
  Ethernet3:
    peer: DC1-LEAF2A
    peer_interface: Ethernet1
    peer_type: l3leaf
    description: P2P_LINK_TO_DC1-LEAF2A_Ethernet1
    mtu: 1500
    type: routed
    shutdown: false
    ip_address: 172.31.255.8/31
  Ethernet4:
    peer: DC1-LEAF2B
    peer_interface: Ethernet1
    peer_type: l3leaf
    description: P2P_LINK_TO_DC1-LEAF2B_Ethernet1
    mtu: 1500
    type: routed
    shutdown: false
    ip_address: 172.31.255.12/31
loopback_interfaces:
  Loopback0:
    description: EVPN_Overlay_Peering
    shutdown: false
    ip_address: 192.168.255.1/32
prefix_lists:
  PL-LOOPBACKS-EVPN-OVERLAY:
    sequence_numbers:
      10:
        action: permit 192.168.255.0/24 eq 32
route_maps:
  RM-CONN-2-BGP:
    sequence_numbers:
      10:
        type: permit
        match:
        - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
router_bfd:
  multihop:
    interval: 1200
    min_rx: 1200
    multiplier: 3
ntp:
  local_interface:
    name: Management1
    vrf: MGMT
  servers:
  - name: 0.fr.pool.ntp.org
    preferred: true
    vrf: MGMT
  - name: 1.fr.pool.ntp.org
    vrf: MGMT
