---
- name: Configlet upload management
  hosts: cv_server
  connection: local
  gather_facts: false
  collections:
    - arista.avd
    - arista.cvp
  tasks:
    - name: upload cvp configlets
      import_role:
        name: arista.avd.cvp_configlet_upload
      vars:
        configlet_directory: 'inventory/intended/configs'
        file_extension: 'cfg'
        configlets_cvp_prefix: 'none'
        execute_tasks: false
        cv_collection: v3
