---
- name: Manage Arista EOS EVPN/VXLAN Configuration
  hosts: DC1_FABRIC
  connection: local
  gather_facts: false
  tasks:
    - name: Reset local folders for output'
      tags: [build, generate]
      ansible.builtin.import_role:
        name: arista.avd.build_output_folders

    - name: Generate intended variables
      tags: [build, generate]
      ansible.builtin.import_role:
        name: arista.avd.eos_designs

    - name: Generate device intended config and documentation
      tags: [build, generate]
      ansible.builtin.import_role:
        name: arista.avd.eos_cli_config_gen

- name: Configuration deployment with CVP
  hosts: cv_server
  connection: local
  gather_facts: false
  tasks:
    - name: Run CVP provisioning
      ansible.builtin.import_role:
        name: arista.avd.eos_config_deploy_cvp
      vars:
        container_root: 'DC1_FABRIC'
        configlets_prefix: 'DC1-AVD'
        device_filter: 'DC1'
        state: present
        cv_collection: v3
