---
# This playbook generates the structured configuration, then
# uses the eos_validate_state to verify whether the states
# on the EOS devices match the structured configuration.

- name: Validate Arista EOS EVPN/VXLAN Configuration
  hosts: DC1_FABRIC
  gather_facts: false
  tasks:
    - name: Generate intended variables
      ansible.builtin.import_role:
        name: arista.avd.eos_designs
      tags: generate

    - name: Validate State
      ansible.builtin.import_role:
        name: arista.avd.eos_validate_state
      vars:
        structured_dir: ../inventory/intended/structured_configs
        eos_validate_state_dir: ../inventory/reports
        validate_state_markdown_flavor: github
      when: is_deployed is not arista.avd.defined(false)
