---
- name: Configure ZTP/DHCP service on CloudVision
  hosts: cv_ztp
  gather_facts: true
  tasks:
    - name: 'Execute ZTP configuration role'
      ansible.builtin.import_role:
        name: arista.cvp.dhcp_configuration
